version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "cloud-resume-challenge"
s3_prefix = "cloud-resume-challenge"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
confirm_changeset = true
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-gwn0412jofzi"
image_repositories = []
dependencies = [
    "requests==2.29.0",
]
