name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
      - uses: cloud-resume-challenge/tests/cypress/integration/cypress_test.cy.js@v1
      - run: cd cloud-resume-challenge/tests/cypress/integration && run cypress_test.cy.js
