name: main
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-22.04
    timeout-minutes: 2
    steps:
    uses: cloud-resume-challenge/tests/cypress/integration/cypress_test.cy.js
      with:
        build: npm run build
        start: npm start

  job-unit: 
    name: Unit Tests
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
    timeout-minutes: 2
    steps:
      - uses: actions/checkout@v3
      - name: pytest_unit_test
        run: cd cloud-resume-challenge/tests/unit && pytest test_handler.py -v
