name: main
on: push

jobs:
  end-to-end-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 14
      - run: cd cloud-resume-challenge/end-to-end-test && npm install && node index.js

      
      
